### ISSUE TITLE
使用机械动力的扳手拆除能量立方导致问题

### ISSUE THREAD

**Issue by starshine123705** [lostmyself8/Mekanism-CraftItem#2]
![QQ_1725159061947](https://github.com/user-attachments/assets/a749cc09-0fe5-4730-b355-661ebe96648f)
报错截图如上，只在装载了该mod后出现对应问题，遂认为可能是该模组的问题

**Comment by starshine123705** [comment]
通过coreprotect找到具体问题，emmm，你这个合成用单元怎么能放置下来的啊

**Comment by lostmyself8** [comment]
这玩意其实能存电，存了电用扳手敲掉就会出问题，我大概知道是啥问题了。

**Comment by lostmyself8** [comment]
> 通过coreprotect找到具体问题，emmm，你这个合成用单元怎么能放置下来的啊

什么单元

**Comment by starshine123705** [comment]
我截了图
![Image_1725161924868.png](https://github.com/user-attachments/assets/e2a39d4b-5a14-477d-be7f-31b45fe857de)

**Comment by starshine123705** [comment]
看得到吗，看不到我就手动打一遍

**Comment by starshine123705** [comment]
那要不设定为放下来不能存电?或者干脆就不能放置

**Comment by lostmyself8** [comment]
我想保留他的模型，但是他模型和方块实体挂钩了，所以他能存电，也能取出来，扳手可以调输入输出，放下去拆掉之后还是会绑定玩家，但是合成一下就全部清除了；后面试试看能不能让他不存电，不过估计不行，他六个面也和电的输入输出绑定了，我不想像原模组那样单纯搞个方块。

**Comment by lostmyself8** [comment]
已经解决了，把物品渲染的代码删掉就行了。

**Comment by starshine123705** [comment]
OK

**Comment by lostmyself8** [comment]
发了

**Comment by starshine123705** [comment]
emmmm

**Comment by starshine123705** [comment]
现在崩溃更严重了

**Comment by starshine123705** [comment]
哦等等，我忘记更新了emmm，光更新服务端了忘记客户端了

**Comment by starshine123705** [comment]
好了，正常

**Comment by starshine123705** [comment]
> 已经解决了，把物品渲染的代码删掉就行了。

[22:06:01 WARN]: Multiple capability resolvers registered for mekanism/api/IConfigurable. Overriding
java.lang.Exception: null
        at mekanism.common.capabilities.CapabilityCache.addCapabilityResolver(CapabilityCache.java:45) ~[%5B通用机械%5D%20
Mekanism-1.20.1-10.4.8.43.jar%23297!/:10.4.8]
        at mekanism.common.tile.base.CapabilityTileEntity.addCapabilityResolver(CapabilityTileEntity.java:37) ~[%5B通用机
械%5D%20Mekanism-1.20.1-10.4.8.43.jar%23297!/:10.4.8]
        at com.jerry.mekanism_extras.common.block.transmitter.ExtraTileEntityTransmitter.<init>(ExtraTileEntityTransmitter
.java:39) ~[mekanism_extras.jar%23344!/:1.2.1]
        at com.jerry.mekanism_extras.common.block.transmitter.pipe.ExtraTileEntityMechanicalPipe.<init>(ExtraTileEntityMec
hanicalPipe.java:36) ~[mekanism_extras.jar%23344!/:1.2.1]
        at com.jerry.mekanism_extras.registry.ExtraTileEntityTypes.lambda$static$25(ExtraTileEntityTypes.java:70) ~[mekani
sm_extras.jar%23344!/:1.2.1]
        at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:92) ~[server-1.20.1-20230
612.114412-srg.jar%23362!/:?]
        at net.minecraft.world.level.block.entity.BlockEntity.m_155236_(BlockEntity.java:136) ~[server-1.20.1-20230612.114
412-srg.jar%23362!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.world.level.block.entity.BlockEntity.m_155241_(BlockEntity.java:134) ~[server-1.20.1-20230612.114
412-srg.jar%23362!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:41) ~[for
ge-1.20.1-47.3.5-universal.jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:27) ~[forge-1.20.
1-47.3.5-universal.jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates$1.createBlockState(CraftBlockStates.java:119) ~[forge-1.
20.1-47.3.5-universal.jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:425) ~[forge-1.20.1-
47.3.5-universal.jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:387) ~[forge-1.20.1-
47.3.5-universal.jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getState(CraftBlock.java:335) ~[forge-1.20.1-47.3.5-universal.
jar%23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getTileEntities(CraftChunk.java:181) ~[forge-1.20.1-47.3.5-universal
.jar%23367!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at me.lucko.spark.bukkit.BukkitWorldInfoProvider.pollCounts(BukkitWorldInfoProvider.java:83) ~[?:?]
        at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.lambda$async$0(AsyncWorldInfoProvider.java:54) ~[?:
?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.5-universal.jar%
23367!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1
.20.1-47.3.5-universal.jar%23367!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1132) ~[server-1.20.1-20230612.114412-srg.jar
%23362!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.11441
2-srg.jar%23362!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1070) ~[server-1.20.1-20230612.114412-srg.jar
%23362!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:909) ~[server-1.20.1-20230612.114412-srg.ja
r%23362!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.ja
r%23362!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by starshine123705** [comment]
之前没抓到的报错，我怀疑问题还没完全修复

**Comment by starshine123705** [comment]
看报错像是重复注册

**Comment by lostmyself8** [comment]
斯，才看到，我看看

**Comment by lostmyself8** [comment]
嗷你这和那边报的一样我已经搞掉了，我看那边只是弹日志，我想等搞完反应堆发来着。
