### ISSUE TITLE
更新MekExtra到CF上的最新版本导致服务端启动出现问题

### ISSUE THREAD

**Issue by starshine123705** [lostmyself8/Mekanism-CraftItem#3]
如下

Forge: net.minecraftforge:47.3.7[00:55:39 ERROR]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mekanism CraftItem（craftitem）无法正确加载
§7java.lang.NoClassDefFoundError: com/jerry/mekanism_extras/common/api/tier/IAdvanceTier
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.3.7.jar%23389!/:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.7.j
ar%23389!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.7.jar%23389!/
:?]
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.7.
jar%23389!/:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.7.jar%23389!
/:?]
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.7-universal
.jar%23393!/:?]
        at net.minecraft.server.Main.main(Main.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23388!/:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-
1.20.1-47.3.7.jar%23192!/:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloa
der-1.20.1-47.3.7.jar%23192!/:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler
.java:27) ~[fmlloader-1.20.1-47.3.7.jar%23192!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-1
0.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:
?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:
?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23
103!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23
103!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:115) [mohist-1.20.1-859-server.jar:1.20.1-859]
在报错里面看到了似乎是无法正确加载某个extra的物品导致的

**Comment by lostmyself8** [comment]
这确实不适配新版本的，等我有空了看看
